### ISSUE TITLE
Credentials for FileMaker files

### ISSUE THREAD

**Issue by micah-woods** [geistinteractive/fmw-calendar#7]
Perhaps I missed it somewhere but I can't find the logon for Calendar.fmp12 and fmw_calendar.fmp12.

Thanks,
Micah

**Comment by toddgeist** [comment]
Hey Micah,

I just pushed a new commit with the user name and password set to `admin` and `demo`

Thanks :-)

**Comment by micah-woods** [comment]
Thanks Todd, what about Calendar.fmp12? I'm doing React development and so I'm looking for the file you use to call the live node server, maybe that's in Calendar?

**Comment by toddgeist** [comment]
fmw_Calendar.fmp12 is the only file we use.

The other one is an old file.  It needs to be removed.

Look in the "FCCalendar Addon Developer Only" folder.  There is a script in there that you can use to load the Dev Server. "FCCalendar Load Calendar"

Todd

**Comment by micah-woods** [comment]
That worked, thanks Todd.

FYI, there's a json parsing error when you call this script with no script param, I changed line 10 to:
```
Let (
	[
		~json = Get ( ScriptParameter ) ;
		~formatted = Left ( JSONFormatElements ( ~json ) ; 1 )
	] ;
	If (
		Left ( ~formatted ; 1 ) = "{" ;
			~json ;
		// Else
			"{}"
	)
)
```

**Comment by toddgeist** [comment]
Thanks :-)
